# exemplo3
spring:
  application:
    name: microservice

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect #depreciado
        dialect: org.hibernate.dialect.MySQLDialect # Em teoria, esse é o default
    show-sql: true
    open-in-view: false # https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG

#Representação em properties
#spring.application.name = microservice
#spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
#spring.datasource.url = jdbc:mysql://localhost:3306/rest_with_spring_boot?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC
#spring.datasource.username = root
#spring.datasource.password = admin123
#
#spring.jpa.generate-ddl = true
#spring.jpa.hibernate.ddl-auto = update
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
#spring.jpa.show-sql = true
#
#logging.level.org.hibernate.SQL = DEBUG
